services:
  - name: flask-mongo-app
    type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: your-mongodb-uri-here
